<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/07/24 06:30:37
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
