<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/07/24 06:30:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet_test',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
