<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/07/20 13:40:13

return array(
'doctrine' => new sfDoctrinedatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
