<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/07/11 07:45:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
